### ***Demonstração Pré-Processamento de Dados***

In [18]:
import pandas as pd

In [19]:
dados = pd.read_csv("C:/Users/anacl/OneDrive/Documents/UFU/LIPAI/Semana07/Preparação dos dados/atp_matches_2021.csv")

In [20]:
dados.head(5)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2021-0096,Tokyo Olympics,Hard,64,A,20210724,237,126207,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,1228.0,71.0,996.0
1,2021-0096,Tokyo Olympics,Hard,64,A,20210724,238,105526,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,48.0,1410.0,95.0,829.0
2,2021-0096,Tokyo Olympics,Hard,64,A,20210724,239,111576,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,160.0,471.0,197.0,354.0
3,2021-0096,Tokyo Olympics,Hard,64,A,20210724,240,105357,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,44.0,1476.0,61.0,1106.0
4,2021-0096,Tokyo Olympics,Hard,64,A,20210724,241,207830,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,145.0,525.0,137.0,570.0


In [21]:
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 2733 entries, 0 to 2732
Data columns (total 49 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   tourney_id          2733 non-null   str    
 1   tourney_name        2733 non-null   str    
 2   surface             2733 non-null   str    
 3   draw_size           2733 non-null   int64  
 4   tourney_level       2733 non-null   str    
 5   tourney_date        2733 non-null   int64  
 6   match_num           2733 non-null   int64  
 7   winner_id           2733 non-null   int64  
 8   winner_seed         1165 non-null   float64
 9   winner_entry        417 non-null    str    
 10  winner_name         2733 non-null   str    
 11  winner_hand         2733 non-null   str    
 12  winner_ht           2731 non-null   float64
 13  winner_ioc          2733 non-null   str    
 14  winner_age          2733 non-null   float64
 15  loser_id            2733 non-null   int64  
 16  loser_seed       

In [22]:
dados.describe(include='all')

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
count,2733,2733,2733,2733.000000,2733,2.733000e+03,2733.000000,2733.000000,1165.000000,417,...,2636.000000,2636.000000,2636.000000,2637.000000,2636.000000,2636.000000,2729.000000,2729.000000,2707.000000,2707.000000
unique,114,114,3,NaN,5,NaN,NaN,NaN,NaN,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-520,Roland Garros,Hard,NaN,A,NaN,NaN,NaN,NaN,Q,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,127,127,1608,NaN,1569,NaN,NaN,NaN,NaN,234,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,62.609587,NaN,2.021060e+07,243.248811,127500.755946,7.687554,NaN,...,50.118361,33.325493,14.494689,12.420554,4.843323,8.714719,70.593624,2229.913888,103.034355,1390.971555
std,NaN,NaN,NaN,41.521804,NaN,2.855522e+02,73.915192,33930.996942,7.133621,NaN,...,19.075552,14.205041,6.857036,4.224477,3.253624,4.126347,103.028379,2484.822372,149.125316,1460.007475
min,NaN,NaN,NaN,2.000000,NaN,2.021010e+07,1.000000,100644.000000,1.000000,NaN,...,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,NaN,NaN,NaN,32.000000,NaN,2.021032e+07,224.000000,105575.000000,3.000000,NaN,...,36.000000,23.000000,10.000000,9.000000,2.000000,6.000000,19.000000,858.000000,37.000000,709.000000
50%,NaN,NaN,NaN,64.000000,NaN,2.021061e+07,276.000000,106432.000000,6.000000,NaN,...,47.000000,31.000000,14.000000,11.000000,4.000000,8.000000,47.000000,1344.000000,68.000000,993.000000
75%,NaN,NaN,NaN,128.000000,NaN,2.021082e+07,289.000000,128034.000000,10.000000,NaN,...,61.000000,42.000000,18.000000,15.000000,7.000000,11.000000,87.000000,2423.000000,112.000000,1595.000000


Detectando valores ausentes.

Retorna um objeto booleano de mesmo tamanho indicando se os valores são NA. Valores NA, como Nenhum ou numpy.NaN, são mapeados para valores verdadeiros. Todo o resto é mapeado para valores falsos. Caracteres como strings vazias ''ou numpy.infnão são considerados valores NA (a menos que você defina ).pandas.options.mode.use_inf_as_na = True

In [23]:
dados.isnull()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False
1,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False
2,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False
3,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False
4,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2728,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False
2729,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False
2730,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False
2731,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,False,False,False,False


Verificar valores nulos nas colunas. Somando os valores nulos de cada coluna.

In [24]:
dados.isnull().sum()

tourney_id               0
tourney_name             0
surface                  0
draw_size                0
tourney_level            0
tourney_date             0
match_num                0
winner_id                0
winner_seed           1568
winner_entry          2316
winner_name              0
winner_hand              0
winner_ht                2
winner_ioc               0
winner_age               0
loser_id                 0
loser_seed            2040
loser_entry           2098
loser_name               0
loser_hand               0
loser_ht                15
loser_ioc                0
loser_age                0
score                    0
best_of                  0
round                    0
minutes                 83
w_ace                   97
w_df                    97
w_svpt                  97
w_1stIn                 97
w_1stWon                97
w_2ndWon                97
w_SvGms                 96
w_bpSaved               97
w_bpFaced               97
l_ace                   97
l

In [25]:
dados['winner_entry'].describe()

count     417
unique      6
top         Q
freq      234
Name: winner_entry, dtype: object

In [26]:
dados['winner_entry'].unique()

<StringArray>
[nan, 'Q', 'WC', 'LL', 'SE', 'Alt', 'PR']
Length: 7, dtype: str

Apagar todas as linhas que o atributo "loser_rank" é nulo, porque são poucas ocasiões e isso pode implicar erros nos resultados.

In [33]:
dados.dropna(subset=['loser_rank'], inplace=True)

In [34]:
dados

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2021-0096,Tokyo Olympics,Hard,64,A,20210724,237,126207,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,1228.0,71.0,996.0
1,2021-0096,Tokyo Olympics,Hard,64,A,20210724,238,105526,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,48.0,1410.0,95.0,829.0
2,2021-0096,Tokyo Olympics,Hard,64,A,20210724,239,111576,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,160.0,471.0,197.0,354.0
3,2021-0096,Tokyo Olympics,Hard,64,A,20210724,240,105357,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,44.0,1476.0,61.0,1106.0
4,2021-0096,Tokyo Olympics,Hard,64,A,20210724,241,207830,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,145.0,525.0,137.0,570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2728,2021-9210,Laver Cup,Hard,8,A,20210924,102,126610,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,5173.0,11.0,3368.0
2729,2021-9210,Laver Cup,Hard,8,A,20210924,103,106421,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,10575.0,12.0,3310.0
2730,2021-9210,Laver Cup,Hard,8,A,20210924,104,126094,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,6130.0,15.0,2800.0
2731,2021-9210,Laver Cup,Hard,8,A,20210924,105,100644,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,7760.0,22.0,2171.0


Apagar colunas que todos os valores são nulos.

In [35]:
dados.dropna(axis=1, how= 'all')

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2021-0096,Tokyo Olympics,Hard,64,A,20210724,237,126207,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,1228.0,71.0,996.0
1,2021-0096,Tokyo Olympics,Hard,64,A,20210724,238,105526,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,48.0,1410.0,95.0,829.0
2,2021-0096,Tokyo Olympics,Hard,64,A,20210724,239,111576,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,160.0,471.0,197.0,354.0
3,2021-0096,Tokyo Olympics,Hard,64,A,20210724,240,105357,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,44.0,1476.0,61.0,1106.0
4,2021-0096,Tokyo Olympics,Hard,64,A,20210724,241,207830,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,145.0,525.0,137.0,570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2728,2021-9210,Laver Cup,Hard,8,A,20210924,102,126610,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,5173.0,11.0,3368.0
2729,2021-9210,Laver Cup,Hard,8,A,20210924,103,106421,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,10575.0,12.0,3310.0
2730,2021-9210,Laver Cup,Hard,8,A,20210924,104,126094,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,6130.0,15.0,2800.0
2731,2021-9210,Laver Cup,Hard,8,A,20210924,105,100644,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,7760.0,22.0,2171.0


Alterar valor dos dados nulos em uma coluna.

In [ ]:
dados['loser_entry'].unique()

<StringArray>
[nan, 'PR', 'Q', 'LL', 'WC', 'SE', 'Alt']
Length: 7, dtype: str

In [36]:
dados['loser_entry'].fillna(value='X',inplace=True)

C:\Users\anacl\AppData\Local\Temp\ipykernel_31732\2380784803.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dados['loser_entry'].fillna(value='X',inplace=True)


0       X
1       X
2       X
3       X
4       X
       ..
2728    X
2729    X
2730    X
2731    X
2732    X
Name: loser_entry, Length: 2707, dtype: str

In [37]:
dados['loser_entry'].unique()

<StringArray>
[nan, 'PR', 'Q', 'LL', 'WC', 'SE', 'Alt']
Length: 7, dtype: str

In [38]:
dados['w_ace'].unique()

array([nan,  5.,  1.,  2.,  3.,  6.,  4., 11.,  8., 15.,  9., 20., 12.,
       24., 14., 17., 13., 19., 10.,  7., 16., 18., 22.,  0., 23., 21.,
       32., 26., 25., 27., 28., 29., 41., 34., 30., 44., 33., 49., 31.,
       36.])

In [39]:
dados['loser_ht'].unique()

array([180., 183., 185., 193., 191., 173., 170., 188., 178., 196., 198.,
       175., 181., 211., 208., 201., 190., 203.,  nan, 189.,  15.])

In [40]:
dados.fillna(value={'w_ace':0,'loser_ht':dados['loser_ht'].mean()},inplace=True)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2021-0096,Tokyo Olympics,Hard,64,A,20210724,237,126207,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,1228.0,71.0,996.0
1,2021-0096,Tokyo Olympics,Hard,64,A,20210724,238,105526,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,48.0,1410.0,95.0,829.0
2,2021-0096,Tokyo Olympics,Hard,64,A,20210724,239,111576,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,160.0,471.0,197.0,354.0
3,2021-0096,Tokyo Olympics,Hard,64,A,20210724,240,105357,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,44.0,1476.0,61.0,1106.0
4,2021-0096,Tokyo Olympics,Hard,64,A,20210724,241,207830,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,145.0,525.0,137.0,570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2728,2021-9210,Laver Cup,Hard,8,A,20210924,102,126610,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,5173.0,11.0,3368.0
2729,2021-9210,Laver Cup,Hard,8,A,20210924,103,106421,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,10575.0,12.0,3310.0
2730,2021-9210,Laver Cup,Hard,8,A,20210924,104,126094,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,6130.0,15.0,2800.0
2731,2021-9210,Laver Cup,Hard,8,A,20210924,105,100644,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,7760.0,22.0,2171.0


In [41]:
dados['w_ace'].unique()

array([ 0.,  5.,  1.,  2.,  3.,  6.,  4., 11.,  8., 15.,  9., 20., 12.,
       24., 14., 17., 13., 19., 10.,  7., 16., 18., 22., 23., 21., 32.,
       26., 25., 27., 28., 29., 41., 34., 30., 44., 33., 49., 31., 36.])

In [42]:
dados['loser_ht'].unique()

array([180.        , 183.        , 185.        , 193.        ,
       191.        , 173.        , 170.        , 188.        ,
       178.        , 196.        , 198.        , 175.        ,
       181.        , 211.        , 208.        , 201.        ,
       190.        , 203.        , 186.73409763, 189.        ,
        15.        ])

### Usar o método ffill para projetar um dado para o registro seguinte

Sinônimo de DataFrame.fillna()com method='ffill'. Devoluções Series/DataFrame ou Nenhum Objeto com valores ausentes preenchidos ou Nenhum se inplace=True.

Método ffill para projetar um dado para o registro seguinte, ou seja, eu pego um dado que está nulo. Pegar o dado do registro anterior e coloco nele. As vezes é um dados de uma série temporal.

In [43]:
dados['minutes'][1975:1990]

1978     67.0
1979    129.0
1980     91.0
1981    140.0
1982     83.0
1983     74.0
1984     90.0
1985     71.0
1986    124.0
1987    140.0
1988    169.0
1989     59.0
1990    130.0
1991    116.0
1992    102.0
Name: minutes, dtype: float64

In [45]:
dados['minutes'] = dados['minutes'].ffill()

In [46]:
dados['minutes'][1975:1990]

1978     67.0
1979    129.0
1980     91.0
1981    140.0
1982     83.0
1983     74.0
1984     90.0
1985     71.0
1986    124.0
1987    140.0
1988    169.0
1989     59.0
1990    130.0
1991    116.0
1992    102.0
Name: minutes, dtype: float64

### Identificar duplicados

In [47]:
dados.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
2728    False
2729    False
2730    False
2731    False
2732    False
Length: 2707, dtype: bool

In [48]:
dados.duplicated().sum()

np.int64(0)

In [49]:
dados.drop_duplicates(subset=['tourney_name'],inplace=True)

In [50]:
dados['tourney_name'].head(10)

0      Tokyo Olympics
64             Munich
91       Queen's Club
122            Gstaad
149           Newport
176            Bastad
203         Kitzbuhel
230         Stuttgart
257            Geneva
284            Vienna
Name: tourney_name, dtype: str

In [51]:
dados.describe()

,draw_size,tourney_date,match_num,winner_id,winner_seed,winner_ht,winner_age,loser_id,loser_seed,loser_ht,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
count,110.000000,1.100000e+02,110.000000,110.000000,11.000000,109.000000,110.000000,110.000000,2.000000,110.000000,...,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,109.000000,109.000000,110.000000,110.000000
mean,28.272727,2.021077e+07,147.463636,132444.963636,2.636364,186.155963,26.620909,127675.763636,7.500000,186.131529,...,46.113208,29.518868,12.481132,10.933962,4.462264,8.141509,130.963303,1659.550459,206.081818,774.890909
std,31.388045,3.299224e+02,127.788578,35819.636900,2.540580,5.927298,4.900966,36480.909687,0.707107,6.804056,...,19.663028,13.125933,5.926906,3.002440,3.604691,4.681145,167.072003,2475.617400,276.922608,722.899353
min,2.000000,2.021010e+07,1.000000,100644.000000,1.000000,170.000000,17.800000,103852.000000,7.000000,170.000000,...,16.000000,5.000000,2.000000,4.000000,0.000000,1.000000,1.000000,7.000000,5.000000,1.000000
25%,4.000000,2.021050e+07,1.000000,105606.250000,1.000000,183.000000,23.550000,105526.000000,7.250000,183.000000,...,33.250000,20.250000,8.000000,9.000000,2.000000,5.000000,42.000000,477.000000,67.000000,238.000000
50%,32.000000,2.021092e+07,239.000000,124940.500000,2.000000,185.000000,25.100000,106165.500000,7.500000,185.000000,...,42.500000,27.000000,12.500000,10.000000,4.000000,7.500000,95.000000,811.000000,101.500000,780.000000
75%,32.000000,2.021111e+07,271.000000,136022.500000,2.000000,191.000000,29.525000,130971.750000,7.750000,191.000000,...,56.000000,37.000000,16.000000,13.000000,6.000000,11.000000,155.000000,1492.000000,251.750000,999.000000
max,128.000000,2.021120e+07,286.000000,209867.000000,9.000000,201.000000,40.100000,208502.000000,8.000000,211.000000,...,165.000000,90.000000,32.000000,18.000000,27.000000,38.000000,1165.000000,12113.000000,1921.000000,5150.000000


### Transformar dados categóricos (qualitativos) em dados numéricos

In [56]:
dados['winner_ioc']

0       USA
64      URU
91      CAN
122     FRA
149     USA
       ... 
2710    RSA
2716    SUI
2720    DEN
2724    TUR
2727    GRE
Name: winner_ioc, Length: 110, dtype: str

In [57]:
dados['winner_ioc'].unique()

<StringArray>
['USA', 'URU', 'CAN', 'FRA', 'ESP', 'SUI', 'ITA', 'GER', 'SWE', 'BLR', 'BIH',
 'GRE', 'SRB', 'RSA', 'GBR', 'FIN', 'BRA', 'IND', 'AUS', 'RUS', 'ARG', 'DEN',
 'CHI', 'BEL', 'SVK', 'KAZ', 'CZE', 'HUN', 'CRO', 'AUT', 'NOR', 'BOL', 'UKR',
 'NED', 'POR', 'TUN', 'DOM', 'LTU', 'BUL', 'POL', 'TUR']
Length: 41, dtype: str

In [59]:
from sklearn.preprocessing import LabelEncoder

In [60]:
paises=dados['winner_ioc']

In [61]:
paises

0       USA
64      URU
91      CAN
122     FRA
149     USA
       ... 
2710    RSA
2716    SUI
2720    DEN
2724    TUR
2727    GRE
Name: winner_ioc, Length: 110, dtype: str

In [62]:
lencoder = LabelEncoder()
paises_numeros = lencoder.fit_transform(paises)
paises_numeros

array([40, 39,  9, 17, 40, 15, 15, 33, 23, 19, 35,  5, 17,  4, 15, 20, 32,
       15, 23, 23, 30, 40, 15, 32,  5, 15, 18, 16, 17,  7, 17, 22, 15, 23,
       18, 19, 15, 23, 32, 32, 32, 32,  1,  7, 17,  5, 31, 18, 40,  0,  0,
       17, 13,  1, 10, 32,  3,  1,  1, 15, 34, 15, 15, 18, 15, 15, 31, 24,
       35, 35, 12, 18, 12, 21, 11, 11, 23, 40, 23,  2, 32, 19, 11, 18, 11,
       31, 31, 31, 24, 27,  5,  6,  4,  7, 10, 16, 38, 26, 29, 27, 36, 14,
       25,  8, 28, 30, 33, 13, 37, 20])

In [63]:
paises.head(10)

0      USA
64     URU
91     CAN
122    FRA
149    USA
176    ESP
203    ESP
230    SUI
257    ITA
284    GER
Name: winner_ioc, dtype: str

In [64]:
dados['paises_numeros']=paises_numeros

In [65]:
dados

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,paises_numeros
0,2021-0096,Tokyo Olympics,Hard,64,A,20210724,237,126207,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,53.0,1228.0,71.0,996.0,40
64,2021-0308,Munich,Clay,32,A,20210426,271,104655,NaN,NaN,...,27.0,13.0,12.0,3.0,7.0,85.0,897.0,62.0,1037.0,39
91,2021-0311,Queen's Club,Grass,32,A,20210614,270,133430,2.0,NaN,...,44.0,18.0,12.0,2.0,2.0,14.0,2780.0,207.0,327.0,9
122,2021-0314,Gstaad,Clay,32,A,20210719,271,126239,NaN,NaN,...,18.0,18.0,10.0,5.0,7.0,100.0,805.0,281.0,200.0,17
149,2021-0315,Newport,Grass,32,A,20210712,271,202195,NaN,NaN,...,16.0,7.0,7.0,8.0,12.0,155.0,473.0,171.0,425.0,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2710,2021-M-DC-2021-WG2-M-RSA-VEN-01,Davis Cup WG2 R1: RSA vs VEN,Hard,4,D,20210918,1,144750,NaN,NaN,...,5.0,4.0,6.0,1.0,7.0,31.0,1758.0,1921.0,1.0,30
2716,2021-M-DC-2021-WG2-M-SUI-EST-01,Davis Cup WG2 R1: SUI vs EST,Hard,4,D,20210917,1,208502,NaN,NaN,...,28.0,10.0,9.0,6.0,8.0,287.0,199.0,717.0,32.0,33
2720,2021-M-DC-2021-WG2-M-THA-DEN-01,Davis Cup WG2 R1: THA vs DEN,Hard,4,D,20210917,1,144841,NaN,NaN,...,28.0,10.0,8.0,6.0,10.0,1083.0,9.0,767.0,27.0,13
2724,2021-M-DC-2021-WG2-M-TUR-LAT-01,Davis Cup WG2 R1: TUR vs LAT,Hard,4,D,20210918,1,123795,NaN,NaN,...,34.0,20.0,11.0,6.0,9.0,170.0,427.0,671.0,38.0,37
